// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD7501_Assignment2_22053458.Data;

#nullable disable

namespace SD7501_Assignment2_22053458.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250407021851_RenameIntoParkingSlotsController")]
    partial class RenameIntoParkingSlotsController
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD7501_Assignment2_22053458.Models.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("ParkingSlotId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSlotId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SD7501_Assignment2_22053458.Models.ParkingSlots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVacant")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K1"
                        },
                        new
                        {
                            Id = 2,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K2"
                        },
                        new
                        {
                            Id = 3,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K3"
                        },
                        new
                        {
                            Id = 4,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K4"
                        },
                        new
                        {
                            Id = 5,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K5"
                        },
                        new
                        {
                            Id = 6,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K6"
                        },
                        new
                        {
                            Id = 7,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K7"
                        },
                        new
                        {
                            Id = 8,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K8"
                        },
                        new
                        {
                            Id = 9,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K9"
                        },
                        new
                        {
                            Id = 10,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K10"
                        },
                        new
                        {
                            Id = 11,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K11"
                        },
                        new
                        {
                            Id = 12,
                            IsVacant = true,
                            Location = "Kensington Avenue",
                            SlotCode = "K12"
                        },
                        new
                        {
                            Id = 13,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H1"
                        },
                        new
                        {
                            Id = 14,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H2"
                        },
                        new
                        {
                            Id = 15,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H3"
                        },
                        new
                        {
                            Id = 16,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H4"
                        },
                        new
                        {
                            Id = 17,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H5"
                        },
                        new
                        {
                            Id = 18,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H6"
                        },
                        new
                        {
                            Id = 19,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H7"
                        },
                        new
                        {
                            Id = 20,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H8"
                        },
                        new
                        {
                            Id = 21,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H9"
                        },
                        new
                        {
                            Id = 22,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H10"
                        },
                        new
                        {
                            Id = 23,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H11"
                        },
                        new
                        {
                            Id = 24,
                            IsVacant = true,
                            Location = "Huia Street",
                            SlotCode = "H12"
                        },
                        new
                        {
                            Id = 25,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U1"
                        },
                        new
                        {
                            Id = 26,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U2"
                        },
                        new
                        {
                            Id = 27,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U3"
                        },
                        new
                        {
                            Id = 28,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U4"
                        },
                        new
                        {
                            Id = 29,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U5"
                        },
                        new
                        {
                            Id = 30,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U6"
                        },
                        new
                        {
                            Id = 31,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U7"
                        },
                        new
                        {
                            Id = 32,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U8"
                        },
                        new
                        {
                            Id = 33,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U9"
                        },
                        new
                        {
                            Id = 34,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U10"
                        },
                        new
                        {
                            Id = 35,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U11"
                        },
                        new
                        {
                            Id = 36,
                            IsVacant = true,
                            Location = "Udy Street",
                            SlotCode = "U12"
                        },
                        new
                        {
                            Id = 37,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A1"
                        },
                        new
                        {
                            Id = 38,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A2"
                        },
                        new
                        {
                            Id = 39,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A3"
                        },
                        new
                        {
                            Id = 40,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A4"
                        },
                        new
                        {
                            Id = 41,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A5"
                        },
                        new
                        {
                            Id = 42,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A6"
                        },
                        new
                        {
                            Id = 43,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A7"
                        },
                        new
                        {
                            Id = 44,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A8"
                        },
                        new
                        {
                            Id = 45,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A9"
                        },
                        new
                        {
                            Id = 46,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A10"
                        },
                        new
                        {
                            Id = 47,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A11"
                        },
                        new
                        {
                            Id = 48,
                            IsVacant = true,
                            Location = "Atiawa Street",
                            SlotCode = "A12"
                        });
                });

            modelBuilder.Entity("SD7501_Assignment2_22053458.Models.Bookings", b =>
                {
                    b.HasOne("SD7501_Assignment2_22053458.Models.ParkingSlots", "ParkingSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("ParkingSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSlot");
                });

            modelBuilder.Entity("SD7501_Assignment2_22053458.Models.ParkingSlots", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
